name = "tamweel-calc"
main = "src/index.tsx"
compatibility_date = "2024-01-01"
node_compat = true

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "tamweel-production"
database_id = "placeholder-for-production-db-id"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "tamweel-attachments-preview"
