name = "tamweel-calc"
main = "src/index.tsx"
compatibility_date = "2024-01-01"
node_compat = true

[build]
command = ""

[[d1_databases]]
binding = "DB"
database_name = "tamweel-production"
database_id = "d625e465-db29-42a0-ace5-5264e6f527f0"


